### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 17: unexpected end of data

### ISSUE THREAD

**Issue by Nircek** [Nircek/telnet-communicator#1]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./main.py", line 26, in handleMsg
    self.callback(s)
  File "./main.py", line 89, in crecv
    self.wtext.insert(END, msg.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 17: unexpected end of data

**Comment by IgorBia** [comment]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 22, in handleMsg
    self.callback(s)
  File "main.py", line 82, in crecv
    self.wtext.insert(END, msg.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 17: invalid start byte
